name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Report Errors
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Build failed: there are uncommitted changes"
            exit 1
          fi
